export const ADD_TO_CART = 'ADD_TO_CART';
export const DECREASE_CART_ITEM = 'DECREASE_CART_ITEM';
export const FETCH_CART_DATA = 'FETCH_CART_DATA';
export const DELETE_CART_ITEM = 'DELETE_CART_ITEM';
export const CLEAR_CART_DATA = 'CLEAR_CART_DATA';
export const CART_UPDATE_STATE = 'CART_UPDATE_STATE';
export const ADD_TO_COMPARE = 'ADD_TO_COMPARE';