export const FETCH_GOOGLELOGIN_REQUEST = 'FETCH_GOOGLELOGIN_REQUEST'
export const FETCH_GOOGLELOGIN_SUCCESS = 'FETCH_GOOGLELOGIN_SUCCESS'
export const FETCH_GOOGLELOGIN_ERROR = 'FETCH_GOOGLELOGIN_ERROR'
